name: "zonificacion-climatica-cte"

channels:
  - defaults
  - bioconda
  - conda-forge

dependencies:
  - snakemake-minimal
  - pygraphviz
  - numpy == 1.19.5
  - pandas == 1.2.4
  - requests == 2.25.1
  - jupyter_core == 4.9.2
  - nbformat == 5.3.0
  